# Generated by Django 6.0.2 on 2026-03-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='theme',
            field=models.CharField(default='common', max_length=250),
        ),
    ]
