# Generated by Django 6.0.2 on 2026-03-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_word_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='learnt',
            field=models.BooleanField(default=False),
        ),
    ]
